repos:
  -
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      -
        id: prettier
        files: '^server/static/js/src/.*\.(js|json|vue)'
  -
    repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      -
        id: black
        types: [python]
  -
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
